name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 10 */3 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "Envoi du ping à Supabase..."
          curl -s -o /dev/null -w "Code de réponse HTTP : %{http_code}\n" \
          -H "apikey: $SUPABASE_KEY" \
          -H "Authorization: Bearer $SUPABASE_KEY" \
          "$SUPABASE_URL/rest/v1/"
